version: "3.8"

networks:  
  warehouse-network:  
    name: warehouse-network  
    driver: bridge

services:
  warehouse-system:
      build:
        context: ./backend/warehousesystem
        dockerfile: Dockerfile
      networks:
        - warehouse-network
      ports:
        - "8080:8080"
      expose:
        - "8080"